export interface EmojiItem {
  name: string;
  unicode: string;
  char: string;
}

export const EMOJI_CATEGORIES: Record<string, EmojiItem[]> = {
  Popular: [
    { name: "Joy", unicode: "1f602", char: "😂" },
    { name: "Heart Eyes", unicode: "1f60d", char: "😍" },
    { name: "Fire", unicode: "1f525", char: "🔥" },
    { name: "Sparkles", unicode: "2728", char: "✨" },
    { name: "Rocket", unicode: "1f680", char: "🚀" },
    { name: "100", unicode: "1f4af", char: "💯" },
    { name: "Trophy", unicode: "1f3c6", char: "🏆" },
    { name: "Star", unicode: "2b50", char: "⭐" },
    { name: "Grinning", unicode: "1f600", char: "😀" },
    { name: "Grinning Big", unicode: "1f603", char: "😃" },
    { name: "Grinning Sweat", unicode: "1f604", char: "😄" },
    { name: "Beaming", unicode: "1f601", char: "😁" },
    { name: "Squinting", unicode: "1f606", char: "😆" },
    { name: "Grinning Sweat Small", unicode: "1f605", char: "😅" },
    { name: "Floor Laughing", unicode: "1f923", char: "🤣" },
    { name: "Slightly Smiling", unicode: "1f642", char: "🙂" },
    { name: "Upside Down", unicode: "1f643", char: "🙃" },
    { name: "Melting", unicode: "1fae0", char: "🫠" },
  ],
  Expressions: [
    { name: "Thinking", unicode: "1f914", char: "🤔" },
    { name: "Cool", unicode: "1f60e", char: "😎" },
    { name: "Clap", unicode: "1f44f", char: "👏" },
    { name: "Party", unicode: "1f973", char: "🥳" },
    { name: "Scream", unicode: "1f631", char: "😱" },
    { name: "Smirk", unicode: "1f60f", char: "😏" },
    { name: "Wink", unicode: "1f609", char: "😉" },
    { name: "Salute", unicode: "1fae1", char: "🫡" },
    { name: "Smiling Eyes", unicode: "1f60a", char: "😊" },
    { name: "Halo", unicode: "1f607", char: "😇" },
    { name: "Smiling Hearts", unicode: "1f970", char: "🥰" },
    { name: "Star Struck", unicode: "1f929", char: "🤩" },
    { name: "Blowing Kiss", unicode: "1f618", char: "😘" },
    { name: "Kissing", unicode: "1f617", char: "😗" },
    { name: "Smiling Static", unicode: "263a", char: "☺️" },
    { name: "Kissing Closed Eyes", unicode: "1f619", char: "😚" },
    { name: "Kissing Smiling Eyes", unicode: "1f61a", char: "😙" },
    { name: "Teardrop Smile", unicode: "1f972", char: "🥲" },
    { name: "Savoring Food", unicode: "1f60b", char: "😋" },
    { name: "Tongue Out", unicode: "1f61c", char: "😛" },
    { name: "Winking Tongue", unicode: "1f61d", char: "😜" },
    { name: "Zany", unicode: "1f92a", char: "🤪" },
    { name: "Squinting Tongue", unicode: "1f61b", char: "😝" },
    { name: "Money Mouth", unicode: "1f911", char: "🤑" },
  ],
  SkepticalAndNeutral: [
    { name: "Hugging", unicode: "1f917", char: "🤗" },
    { name: "Hand Over Mouth", unicode: "1f92d", char: "🤭" },
    { name: "Peeking", unicode: "1fae3", char: "🫣" },
    { name: "Eyes Covered", unicode: "1fae2", char: "🫢" },
    { name: "Shushing", unicode: "1f92b", char: "🤫" },
    { name: "Zipper Mouth", unicode: "1f910", char: "🤐" },
    { name: "Raised Eyebrow", unicode: "1f928", char: "🤨" },
    { name: "Neutral", unicode: "1f610", char: "😐" },
    { name: "Expressionless", unicode: "1f611", char: "😑" },
    { name: "Dotted Line", unicode: "1fae5", char: "🫥" },
    { name: "Unamused", unicode: "1f612", char: "😒" },
    { name: "Rolling Eyes", unicode: "1f644", char: "🙄" },
    { name: "Grimacing", unicode: "1f62c", char: "😬" },
    { name: "Lying Face", unicode: "1f925", char: "🤥" },
    { name: "Shaking Face", unicode: "1fae8", char: "🫨" },
    { name: "Relieved", unicode: "1f60c", char: "😌" },
    { name: "Pensive", unicode: "1f614", char: "😔" },
    { name: "Sleepy", unicode: "1f62a", char: "😪" },
    { name: "Drooling", unicode: "1f924", char: "🤤" },
    { name: "Sleeping", unicode: "1f634", char: "😴" },
  ],
  UnwellAndDistressed: [
    { name: "Masked", unicode: "1f637", char: "😷" },
    { name: "Thermometer", unicode: "1f912", char: "🤒" },
    { name: "Bandage", unicode: "1f915", char: "🤕" },
    { name: "Nauseous", unicode: "1f922", char: "🤢" },
    { name: "Vomiting", unicode: "1f92e", char: "🤮" },
    { name: "Sneezing", unicode: "1f92f", char: "🤧" },
    { name: "Hot", unicode: "1f975", char: "🥵" },
    { name: "Cold", unicode: "1f976", char: "🥶" },
    { name: "Woozy", unicode: "1f974", char: "🥴" },
    { name: "Dizzy", unicode: "1f635", char: "😵" },
    { name: "Exploding Head", unicode: "1f92f", char: "🤯" },
    { name: "Cowboy", unicode: "1f920", char: "🤠" },
    { name: "Disguised", unicode: "1f978", char: "🥸" },
    { name: "Nerd", unicode: "1f913", char: "🤓" },
    { name: "Monocle", unicode: "1f9d0", char: "🧐" },
    { name: "Slightly Frowning", unicode: "1f641", char: "🙁" },
    { name: "Frowning", unicode: "2639", char: "☹️" },
    { name: "Worried", unicode: "1f61f", char: "😟" },
    { name: "Confused", unicode: "1f615", char: "😕" },
    { name: "Disappointed", unicode: "1f61e", char: "😞" },
    { name: "Arguing", unicode: "1f624", char: "😤" },
    { name: "Crying", unicode: "1f622", char: "😢" },
    { name: "Loudly Crying", unicode: "1f62d", char: "😭" },
    { name: "Frowning Open Mouth", unicode: "1f626", char: "😦" },
    { name: "Anguished", unicode: "1f627", char: "😧" },
    { name: "Fearful", unicode: "1f628", char: "😨" },
    { name: "Weary", unicode: "1f629", char: "😩" },
    { name: "Tired Face", unicode: "1f62b", char: "😫" },
    { name: "Yawning", unicode: "1f971", char: "🥱" },
    { name: "Anxious Sweat", unicode: "1f630", char: "😰" },
    { name: "Sad Sweat", unicode: "1f613", char: "😓" },
    { name: "Cold Sweat", unicode: "1f625", char: "😥" },
    { name: "Confounded", unicode: "1f616", char: "😖" },
    { name: "Astonished", unicode: "1f632", char: "😲" },
    { name: "Flushed Red", unicode: "1f633", char: "😳" },
    { name: "Pleading", unicode: "1f97a", char: "🥺" },
    { name: "Holding Back Tears", unicode: "1f979", char: "🥹" },
    { name: "Frowning Mouth Open", unicode: "1f62e", char: "😮" },
    { name: "Hushed", unicode: "1f62f", char: "😯" },
    { name: "Persevering", unicode: "1f623", char: "😣" },
    { name: "Angry", unicode: "1f620", char: "😠" },
    { name: "Pouting Mad", unicode: "1f621", char: "😡" },
    { name: "Cursing Symbols", unicode: "1f92c", char: "🤬" },
  ],
  Shapes: [
    { name: "Red Heart", unicode: "2764", char: "❤️" },
    { name: "Warning", unicode: "26a0", char: "⚠️" },
    { name: "Target", unicode: "1f3af", char: "🎯" },
    { name: "Boom", unicode: "1f4a5", char: "💥" },
    { name: "Diamond", unicode: "1f48e", char: "💎" },
    { name: "Lightning", unicode: "26a1", char: "⚡" },
  ],
};

export function getTwemojiUrl(unicode: string): string {
  return `https://cdn.jsdelivr.net/gh/jdecked/twemoji@latest/assets/svg/${unicode}.svg`;
}